#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This J-JOB script runs the preprocess of retrieving the firstguess of 
# ocean signifcant wave height (HOWV) and 10-m wind-gust (GUST) field
# from WW3 forecasts (script originally based on JURMA_GETGUESS of 2DURMA)
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs an ocean significant wave
height (howv) and 10-m wind gust (gust) preprocess with FV3-LAM for the 
specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Define the path to WW3 firstguess
#
#-----------------------------------------------------------------------
#
export COMINww3GL=/lfs/h1/ops/prod/com/glwu/v2.0                                 # v1.1 is old
export COMINww3=/lfs/h1/ops/prod/com/gfs/v16.3                                   # v16.2 is old

# check the path to RRFS prod
export RRFS_PRODROOT=${RRFS_PRODROOT:-/lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod}
export COMIN_prod_rrfs=${COMIN_prod_rrfs:-/lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod}

# path to the scripts
export HOMEscript=${SCRIPTSdir}
#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
#
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export workdir=${CYCLE_DIR}/process_howv_spinup
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
    workdir=${CYCLE_DIR}/process_radarref_howv_enkf
  fi
else
  export workdir=${CYCLE_DIR}/process_howv
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
    workdir=${CYCLE_DIR}/process_howvf_enkf
  fi
fi
rm -fr ${workdir}
mkdir -p ${workdir}
cd ${workdir}
#
export gridspec_dir=${NWGES_BASEDIR}/grid_spec
#
#-----------------------------------------------------------------------
#
# create COMOUT directory
#
#-----------------------------------------------------------------------
#
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup"
else
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}"
fi
mkdir -p "${COMOUT}"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job.
#
#-----------------------------------------------------------------------
#
export pgmout="${workdir}/OUTPUT.$$"
env

$SCRIPTSdir/exrrfs_process_howvgust.sh \
  CYCLE_DIR="${CYCLE_DIR}"
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

