#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This J-JOB script runs after the analysi to regrid the 2-D fileds of
#      analysis of ocean siginificantg wave height (HOWV) and 10-m wind
#      gust (GUST) from the Extended Schmidt Gnomonic (ESG) grid to 
#      Rotated LatLon (RLL) grid.
#
#-----------------------------------------------------------------------

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a analysis with FV3 for 
the specified cycle.
========================================================================"

# path to the scripts
export HOMEscript=${SCRIPTSdir}

#
#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
#
# CYCLE_TYPE is to indicate which type of cycle this job for:
#   spinup: this job is for spin-up cycles
#   others(prod): this job is for product cycle
#
export CYCLE_TYPE=${CYCLE_TYPE:-prod}
export CYCLE_SUBTYPE=${CYCLE_SUBTYPE:-empty}
export ctrlpath=""
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export modelinputdir=${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam_spinup/INPUT
  if [ "${DO_ENSINIT}" = "TRUE" ] && [ "${CYCLE_SUBTYPE}" = "ensinit" ]; then
    modelinputdir=${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam_ensinit/INPUT
  fi
  if [ "${DO_ENSINIT}" = "TRUE" ] && [ "${CYCLE_SUBTYPE}" = "spinup" ]; then
    ctrlpath=${ENSCTRL_CYCLE_DIR}
  fi
else
  export modelinputdir=${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/fcst_fv3lam/INPUT
fi

if [[ ! -d ${modelinputdir} ]]; then
  echo "cannot find model fcst input directory. Abort..."
  exit 
fi
cd ${modelinputdir}
#
export gridspec_dir=${NWGES_BASEDIR}/grid_spec
export MAILTO="${MAILTO:-}"

if [ "${CYCLE_TYPE}" = "spinup" ]; then
  analworkname="_gsi_spinup"
else
  analworkname="_gsi"
fi

if [[ ! -v OB_TYPE ]]; then
  OB_TYPE="conv"
fi
if [ "${GSI_TYPE}" = "OBSERVER" ]; then
  if [ "${MEM_TYPE}" = "MEAN" ]; then
    analworkdir="${CYCLE_DIR}/ensmean/observer${analworkname}"
    SLASH_ENSMEM_SUBDIR=""
  else
    analworkdir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/observer${analworkname}"
  fi
else
  analworkdir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/anal_${OB_TYPE}${analworkname}"
fi

#
#-----------------------------------------------------------------------
#
# create COMOUT directory
#
#-----------------------------------------------------------------------
#
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${HH}_spinup"
else
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${HH}"
fi
mkdir -p "${COMOUT}"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job.
#
#-----------------------------------------------------------------------
#
export pgmout="${modelinputdir}/OUTPUT.$$"
env

$SCRIPTSdir/exrrfs_run_postanal_howvgust.sh \
             cycle_dir="${CYCLE_DIR}" \
             gsi_type="${GSI_TYPE}" \
             ob_type="${OB_TYPE}" \
             mem_type="${MEM_TYPE}" \
             slash_ensmem_subdir="${SLASH_ENSMEM_SUBDIR}" \
             fg_root="${FG_ROOT}" \
             analworkdir="${analworkdir}"
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

